create table if not exists public.class_sessions (
    id uuid primary key default gen_random_uuid(),
    subject_id bigint not null references public.subjects(subject_id) on delete cascade,
    teacher_id bigint not null references public.teachers(teacher_id) on delete cascade,
    start_time timestamptz not null default now(),
    end_time timestamptz,
    date date not null default current_date,
    status text not null default 'running' check (status in ('running', 'ended'))
);

create table if not exists public.student_analytics (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(student_id) on delete cascade,
    subject_id bigint not null references public.subjects(subject_id) on delete cascade,
    session_id uuid not null references public.class_sessions(id) on delete cascade,
    present_duration integer not null default 0,
    focused_duration integer not null default 0,
    distracted_duration integer not null default 0,
    phone_usage_duration integer not null default 0,
    drowsy_duration integer not null default 0,
    away_duration integer not null default 0,
    engagement_score numeric(5,2) not null default 0,
    engagement_level text not null default 'VERY LOW',
    updated_at timestamptz not null default now(),
    unique (student_id, subject_id, session_id)
);

create table if not exists public.behaviour_events (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(student_id) on delete cascade,
    subject_id bigint not null references public.subjects(subject_id) on delete cascade,
    session_id uuid not null references public.class_sessions(id) on delete cascade,
    event_type text not null,
    start_time timestamptz not null,
    end_time timestamptz,
    duration integer not null default 0,
    confidence numeric(4,3),
    metadata jsonb not null default '{}'::jsonb
);

alter table public.attendance_logs
    add column if not exists session_id uuid references public.class_sessions(id) on delete set null;

create index if not exists idx_class_sessions_teacher_subject_date
    on public.class_sessions(teacher_id, subject_id, date desc);
create index if not exists idx_student_analytics_session
    on public.student_analytics(session_id, subject_id, student_id);
create index if not exists idx_behaviour_events_session_student
    on public.behaviour_events(session_id, student_id, start_time);
create index if not exists idx_attendance_logs_session
    on public.attendance_logs(session_id, student_id);
create unique index if not exists uniq_attendance_logs_session_student
    on public.attendance_logs(session_id, student_id)
    where session_id is not null;

-- RLS note:
-- The current app uses a custom teachers table/password login instead of Supabase Auth.
-- Enabling RLS here without auth.uid()-mapped teacher identities would block the existing
-- Streamlit client queries. Keep the app constrained by teacher_id filters for now, and
-- enable RLS when teacher accounts are migrated to Supabase Auth.
